### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by NuclearRedeye** [NuclearRedeye/zenhub#1]
# User Stories
_As a **developer**, I want a standard set of issue templates so that new issues raised in the repository adhere to a specific standard._

# Description
Issue Templates in GitHub are great for ensuring that new issues raised adhere to a standard and that all the relevant information is captured to make sure the issue is as easy to work as possible.

# Tasks
- [ ] Create an issue template for a 'Feature'
- [ ] Create an issue template for a 'Task'
- [ ] Create an issue template for a 'Bug'

# Definition of Done
- [ ] Issue templates committed to [this](https://github.com/NuclearRedeye/zenhub) repository
- [ ] User can when raising a new issue, select from the available templates.
- [ ] Templates reviewed and approved by the relevant stakeholders.
